[package]
name = "tanxium"
version = "0.1.0"
edition = "2021"


[dependencies]
uuid = { version = "1.10.0", default-features = false, features = [
    "v4",
    "fast-rng",
] }
boa_engine = "0.19.0"
boa_gc = "0.19.0"
deno_ast = { version = "0.42.0", features = ["transpiling", "typescript"] }
boa_parser = "0.19.0"
futures-util = "0.3.30"
smol = "2.0.2"
reqwest = { version = "0.12.7", features = ["blocking"] }
